service: cryptance-bot
app: cryptance
org: suphero

frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  status:
    handler: src/handler.statusHandler
    events:
      - httpApi:
          path: /
          method: get
    environment:
      TELEGRAM_BOT_TOKEN: ${param:TELEGRAM_BOT_TOKEN}
      ENDPOINT_URL: ${param:ENDPOINT_URL}
      WEBHOOK_PATH: "api"
      DEBUG: ${param:DEBUG}
      DEBUG_COLORS: "no"
  webhook:
    handler: src/handler.webhookHandler
    events:
      - httpApi:
          path: /api
          method: post
    environment:
      TELEGRAM_BOT_TOKEN: ${param:TELEGRAM_BOT_TOKEN}
      ENDPOINT_URL: ${param:ENDPOINT_URL}
      DEBUG: ${param:DEBUG}
      DEBUG_COLORS: "no"
      NEXT_REMINDER_DAYS: ${param:NEXT_REMINDER_DAYS}
